# Generated by Django 4.0.3 on 2023-02-26 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rarity', models.IntegerField()),
                ('resource_used_wrath', models.IntegerField(default=0)),
                ('resource_used_lust', models.IntegerField(default=0)),
                ('resource_used_sloth', models.IntegerField(default=0)),
                ('resource_used_gluttony', models.IntegerField(default=0)),
                ('resource_used_gloom', models.IntegerField(default=0)),
                ('resource_used_pride', models.IntegerField(default=0)),
                ('resource_used_envy', models.IntegerField(default=0)),
                ('skills', models.TextField()),
                ('passive_on_field', models.TextField(blank=True, null=True)),
                ('passive_off_field', models.TextField(blank=True, default=None, null=True)),
                ('resistance_wrath', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_lust', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_sloth', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_gluttony', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_gloom', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_pride', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_envy', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_slash', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_pierce', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_blunt', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('rarity', models.IntegerField()),
                ('passive_on_field', models.TextField(blank=True, null=True)),
                ('passive_off_field', models.TextField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('resistance_wrath', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_lust', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_sloth', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_gluttony', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_gloom', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_pride', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_envy', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_slash', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_pierce', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('resistance_blunt', models.CharField(choices=[('F', 'Fatal'), ('W', 'Weak'), ('N', 'Normal'), ('E', 'Endured'), ('I', 'Ineffective')], default='N', max_length=1)),
                ('sinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='limbus.sinner')),
            ],
        ),
    ]
