# Generated by Django 4.0.3 on 2023-02-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0003_passive_passiveabnormality_passiveego_passiveenemy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('in_game_id', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('coindescs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='passive',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passiveabnormality',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passiveego',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passiveenemy',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
