# Generated by Django 4.0.3 on 2023-02-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0004_skill_alter_passive_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('in_game_id', models.CharField(max_length=10)),
                ('level', models.IntegerField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('abName', models.CharField(max_length=30)),
                ('coindescs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ego',
            name='awakening_skill',
        ),
        migrations.RemoveField(
            model_name='ego',
            name='corrision_skill',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='skill_3',
        ),
    ]
