# Generated by Django 4.0.3 on 2023-02-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0005_skillego_remove_ego_awakening_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ego',
            name='awakening_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awakening_skill', to='limbus.skillego'),
        ),
        migrations.AddField(
            model_name='ego',
            name='corrision_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrision_skill', to='limbus.skillego'),
        ),
        migrations.AddField(
            model_name='identity',
            name='skill_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_1', to='limbus.skill'),
        ),
        migrations.AddField(
            model_name='identity',
            name='skill_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_2', to='limbus.skill'),
        ),
        migrations.AddField(
            model_name='identity',
            name='skill_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_3', to='limbus.skill'),
        ),
    ]
