# Generated by Django 4.0.3 on 2023-02-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0007_remove_ego_passive_off_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ego',
            name='passive_off_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passive_off_field', to='limbus.passiveego'),
        ),
        migrations.AddField(
            model_name='ego',
            name='passive_on_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passive_on_field', to='limbus.passiveego'),
        ),
        migrations.AddField(
            model_name='identity',
            name='passive_off_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passive_off_field', to='limbus.passive'),
        ),
        migrations.AddField(
            model_name='identity',
            name='passive_on_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passive_on_field', to='limbus.passive'),
        ),
    ]
