# Generated by Django 4.0.3 on 2023-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0008_ego_passive_off_field_ego_passive_on_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='coin_mod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='coin_roll',
            field=models.TextField(blank=True, null=True),
        ),
    ]
