# Generated by Django 4.0.3 on 2023-02-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0009_skill_coin_mod_skill_coin_roll'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ego',
            name='awakening_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awakening_skill', to='limbus.skillego'),
        ),
        migrations.AlterField(
            model_name='ego',
            name='corrision_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrision_skill', to='limbus.skillego'),
        ),
        migrations.AlterField(
            model_name='ego',
            name='passive_off_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_off_field', to='limbus.passiveego'),
        ),
        migrations.AlterField(
            model_name='ego',
            name='passive_on_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_on_field', to='limbus.passiveego'),
        ),
        migrations.AlterField(
            model_name='ego',
            name='sinner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='limbus.sinner'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='passive_off_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_off_field', to='limbus.passive'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='passive_on_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_on_field', to='limbus.passive'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='sinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='limbus.sinner'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='skill_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_1', to='limbus.skill'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='skill_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_2', to='limbus.skill'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='skill_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_3', to='limbus.skill'),
        ),
    ]
