# Generated by Django 4.0.3 on 2023-02-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0010_battlekeywords_alter_ego_awakening_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlekeywords',
            name='in_game_id',
            field=models.CharField(max_length=30),
        ),
    ]
