# Generated by Django 4.0.3 on 2023-02-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0011_alter_battlekeywords_in_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ego',
            name='in_game_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='in_game_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
