# Generated by Django 4.0.3 on 2023-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0012_ego_in_game_id_identity_in_game_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='coin_mod',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='coin_roll',
        ),
        migrations.AddField(
            model_name='identity',
            name='affinity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='base_damage',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='growth',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='skill_1_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='identity',
            name='skill_2_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='identity',
            name='skill_3_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='skillego',
            name='coin_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillego',
            name='coin_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillego',
            name='coin_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillego',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
