# Generated by Django 4.0.3 on 2023-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0013_remove_skill_coin_mod_remove_skill_coin_roll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='coin_mod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='coin_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='coin_roll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
