# Generated by Django 4.0.3 on 2023-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0015_alter_identity_base_damage_alter_identity_growth'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='damage_type',
            field=models.CharField(default='Blunt', max_length=30),
        ),
        migrations.AddField(
            model_name='skillego',
            name='damage_type',
            field=models.CharField(default='Blunt', max_length=30),
        ),
    ]
