# Generated by Django 4.0.3 on 2023-03-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbus', '0016_skill_damage_type_skillego_damage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='affinity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
