# Generated by Django 4.1.7 on 2023-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0017_alter_identity_affinity"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillego",
            name="emotion_type",
            field=models.CharField(
                choices=[("A", "Awakening"), ("C", "Corrision")],
                default="A",
                max_length=1,
            ),
        ),
    ]
