# Generated by Django 4.1.7 on 2023-03-19 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0018_skillego_emotion_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillego",
            name="character",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="limbus.sinner",
            ),
        ),
    ]
