# Generated by Django 4.1.7 on 2023-04-11 22:20

from django.db import migrations
import limbus.models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0020_remove_skill_coindescs_remove_skillego_coindescs"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="coindescs",
            field=limbus.models.NonStrippingTextField(blank=True),
        ),
        migrations.AddField(
            model_name="skillego",
            name="coindescs",
            field=limbus.models.NonStrippingTextField(blank=True),
        ),
    ]
