# Generated by Django 4.1.7 on 2024-08-06 03:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0021_skill_coindescs_skillego_coindescs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="desc",
            new_name="combat_start",
        ),
        migrations.RenameField(
            model_name="skill",
            old_name="coin_num",
            new_name="skill_num",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="affinity",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="base_damage",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="growth",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="in_game_id",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="is_in_game",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="passive_off_field",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="passive_on_field",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_envy",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_gloom",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_gluttony",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_lust",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_pride",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_sloth",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="resistance_wrath",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="skill_1",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="skill_1_count",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="skill_2",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="skill_2_count",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="skill_3",
        ),
        migrations.RemoveField(
            model_name="identity",
            name="skill_3_count",
        ),
        migrations.RemoveField(
            model_name="passive",
            name="in_game_id",
        ),
        migrations.RemoveField(
            model_name="passiveabnormality",
            name="in_game_id",
        ),
        migrations.RemoveField(
            model_name="passiveego",
            name="in_game_id",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="damage_type",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="in_game_id",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="level",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="type",
        ),
        migrations.AddField(
            model_name="identity",
            name="defense",
            field=models.IntegerField(default=43, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="panic",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="passive",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="support_passive",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="belonged_identity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity",
                to="limbus.identity",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="on_use",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="sin_type",
            field=models.CharField(
                choices=[
                    ("WR", "Wrath"),
                    ("LU", "Lust"),
                    ("SL", "Sloth"),
                    ("GU", "Gluttony"),
                    ("GL", "Gloom"),
                    ("PR", "Pride"),
                    ("EN", "Envy"),
                ],
                default="WR",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[
                    ("BT", "Blunt"),
                    ("PI", "Pierce"),
                    ("SL", "Slash"),
                    ("BK", "Block"),
                    ("EV", "Evade"),
                    ("CO", "Counter"),
                ],
                default="BT",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="coindescs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True), size=None
            ),
        ),
    ]
