# Generated by Django 4.1.7 on 2024-08-07 00:37

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0022_rename_desc_skill_combat_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="coindescs",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True), size=None
            ),
        ),
    ]
