# Generated by Django 4.1.7 on 2024-08-07 00:43

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0023_alter_skill_coindescs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="coindescs",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=400, null=True),
                size=8,
            ),
        ),
    ]
