# Generated by Django 4.1.7 on 2024-08-07 00:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0024_alter_skill_coindescs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="coindescs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True), size=None
            ),
        ),
    ]
