# Generated by Django 4.1.7 on 2024-08-07 01:18

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0027_alter_skill_coindescs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="coindescs",
            field=django_jsonform.models.fields.ArrayField(
                base_field=django_jsonform.models.fields.ArrayField(
                    base_field=models.CharField(blank=True, max_length=254), size=8
                ),
                size=8,
            ),
        ),
    ]
