# Generated by Django 4.1.7 on 2024-08-07 01:28

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0028_alter_skill_coindescs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="coindescs",
            field=django_jsonform.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=254, null=True),
                size=8,
            ),
        ),
    ]
