# Generated by Django 4.1.7 on 2024-08-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0031_alter_skill_coindescs"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="coin_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
