# Generated by Django 4.1.7 on 2024-08-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0032_skill_coin_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="power",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
