# Generated by Django 4.1.7 on 2024-08-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus", "0033_skill_power"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
