# Generated by Django 4.1.7 on 2024-08-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="egoattributeresist",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
