# Generated by Django 4.1.7 on 2024-09-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "limbus2",
            "0003_enstagechapter_enstagenode_modeltochar_storytheater_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ENStoryChaptersModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "chapterNumber",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stageDetail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "chaptertitle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("chapter", models.CharField(blank=True, max_length=100, null=True)),
                ("node_index", models.IntegerField(blank=True, null=True)),
                (
                    "story_theather_list_node_id",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
