# Generated by Django 4.1.7 on 2025-01-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("limbus2", "0004_enstorychaptersmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enpassivedescription",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="enskilleffect",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
