# Generated by Django 3.2.9 on 2021-12-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
