# Generated by Django 3.2.9 on 2021-12-03 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LoR", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guide",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guide",
            name="required_decks",
            field=models.ManyToManyField(through="LoR.RelGuide", to="LoR.Deck"),
        ),
        migrations.AddField(
            model_name="deck",
            name="Recc_Floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LoR.office",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="Recc_Page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LoR.page",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="Recc_Rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LoR.rank",
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="cards",
            field=models.ManyToManyField(through="LoR.RelDeck", to="LoR.Card"),
        ),
        migrations.AddField(
            model_name="deck",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deck",
            name="effect",
            field=models.ManyToManyField(to="LoR.Effects"),
        ),
        migrations.AddField(
            model_name="character",
            name="Page",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="LoR.page"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="LoR.office"
            ),
        ),
        migrations.AddField(
            model_name="abnocards",
            name="office",
            field=models.ForeignKey(
                limit_choices_to={"Rank": 7},
                on_delete=django.db.models.deletion.CASCADE,
                to="LoR.office",
            ),
        ),
    ]
