# Generated by Django 3.2.9 on 2022-03-08 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='effects',
            name='Guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoR.office'),
        ),
        migrations.AddField(
            model_name='effects',
            name='Rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoR.rank'),
        ),
        migrations.AddField(
            model_name='effects',
            name='Rarity',
            field=models.CharField(choices=[('P', 'Paperback'), ('H', 'Hardcover'), ('L', 'Limited'), ('O', "Objet d'art"), ('E', 'EGO')], default='P', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='effects',
            name='Transferable',
            field=models.BooleanField(null=True),
        ),
    ]
