# Generated by Django 3.2.9 on 2022-03-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0003_auto_20220307_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='EnemyOnly',
            field=models.BooleanField(null=True),
        ),
    ]
