# Generated by Django 4.1.7 on 2023-06-22 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("LoR", "0004_effects_enemyonly"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="creator_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_new",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # migrations.AlterField(
        #     model_name="card",
        #     name="office",
        #     field=models.ForeignKey(
        #         null=True, on_delete=django.db.models.deletion.CASCADE, to="LoR.office"
        #     ),
        # ),
    ]
